# Generated by Django 6.0.5 on 2026-06-21 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='height',
            new_name='length',
        ),
    ]
